version: "2"
services:
 app:
  build: .
  image: chuongdang/netaspcore-sample
  container_name: app
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
  command: dotnet ef database update
  ports:
   - "80:80"
  networks:
   - back-tier

networks:
  back-tier:

